# Generated by Django 5.2.7 on 2025-10-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submission_id',
            new_name='submission',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='class_id',
            new_name='class_obj',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='class_id',
            new_name='class_obj',
        ),
        migrations.RemoveField(
            model_name='class',
            name='invites',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
    ]
