# Generated by Django 5.2.7 on 2025-10-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
