# Generated by Django 5.2.7 on 2025-10-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_class_class_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
