##############################################
# USERS API
##############################################

###
# List all users
GET http://localhost:8000/api/users/
###

# Get user details by email
GET http://localhost:8000/api/users/email/isa@example.com/
###

# Get user details by ID
GET http://localhost:8000/api/users/id/900105c9-c7a9-4ab4-a991-8ec31042776f/
###

# Create a new user
POST http://localhost:8000/api/users/
Content-Type: application/json

{
  "username": "test2",
  "email": "test@gmail.com",
  "profile_picture": "https://picsum.photos/200/300",
  "is_active": false
}
###

# Update (patch) a user by email
PATCH http://localhost:8000/api/users/email/user1@gmail.com/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5ODQ5MTEwLCJpYXQiOjE3NTk4NDc5MTAsImp0aSI6IjA4Yjk2MzMwZDFhYzQ4MGFiMDRhMWU0NThlODRmMzNhIiwidXNlcl9pZCI6Ijg1MGU1Yzg0LTAxNGMtNGZmOC04NmIxLWFiZWI1YmE4YzY2OCIsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIn0.-Pa12598YMivpbvDKETyDsFf8eL4ojB24nn4kLfWYDc

{
  "username": "user1_updated"
}
###

# Delete a user by email
# NOTE: Must include trailing slash
DELETE http://localhost:8000/api/users/email/san@example.com/
###

##############################################
# JWT TOKEN (DEV ENDPOINT)
##############################################

# Create or get JWT token by email
POST http://localhost:8000/api/dev/get-token/
Content-Type: application/json

{
  "email": "sadiaa@example.com"
}

##############################################
# CLASS API TESTS
##############################################

###
# Create a new class
POST http://localhost:8000/api/class/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5ODQ5MTEwLCJpYXQiOjE3NTk4NDc5MTAsImp0aSI6IjA4Yjk2MzMwZDFhYzQ4MGFiMDRhMWU0NThlODRmMzNhIiwidXNlcl9pZCI6Ijg1MGU1Yzg0LTAxNGMtNGZmOC04NmIxLWFiZWI1YmE4YzY2OCIsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIn0.-Pa12598YMivpbvDKETyDsFf8eL4ojB24nn4kLfWYDc

{
  "class_name": "Chemistry 101",
  "description": "Introduction to basic chemistry concepts for beginners."
}
###

# Get all classes
GET http://localhost:8000/api/class/
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5ODQ5MTEwLCJpYXQiOjE3NTk4NDc5MTAsImp0aSI6IjA4Yjk2MzMwZDFhYzQ4MGFiMDRhMWU0NThlODRmMzNhIiwidXNlcl9pZCI6Ijg1MGU1Yzg0LTAxNGMtNGZmOC04NmIxLWFiZWI1YmE4YzY2OCIsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIn0.-Pa12598YMivpbvDKETyDsFf8eL4ojB24nn4kLfWYDc
###

# Get class details by ID
GET http://localhost:8000/api/class/8043eedd-da65-449b-970a-6aecff477691/
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5ODQ5MTEwLCJpYXQiOjE3NTk4NDc5MTAsImp0aSI6IjA4Yjk2MzMwZDFhYzQ4MGFiMDRhMWU0NThlODRmMzNhIiwidXNlcl9pZCI6Ijg1MGU1Yzg0LTAxNGMtNGZmOC04NmIxLWFiZWI1YmE4YzY2OCIsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIn0.-Pa12598YMivpbvDKETyDsFf8eL4ojB24nn4kLfWYDc
###

# Update a class by ID
PATCH http://localhost:8000/api/class/8043eedd-da65-449b-970a-6aecff477691/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5ODQ5MTEwLCJpYXQiOjE3NTk4NDc5MTAsImp0aSI6IjA4Yjk2MzMwZDFhYzQ4MGFiMDRhMWU0NThlODRmMzNhIiwidXNlcl9pZCI6Ijg1MGU1Yzg0LTAxNGMtNGZmOC04NmIxLWFiZWI1YmE4YzY2OCIsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIn0.-Pa12598YMivpbvDKETyDsFf8eL4ojB24nn4kLfWYDc

{
  "class_name": "Chemistry 101 - Updated",
  "description": "Updated description: Introduction to basic chemistry concepts for beginners."
}

###
 #join a class by class code
POST http://localhost:8000/api/class/3CYILX9/join/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5ODY2MzA5LCJpYXQiOjE3NTk4NjUxMDksImp0aSI6ImU2MjIzMjlhNGQzZTQ0ZTA4NTdmNTQ2YzRlOWMxZDI1IiwidXNlcl9pZCI6IjExY2NmNDMwLTg5NmItNDA4Mi04MTAzLTZhM2ZjMjdjNGJkNiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIn0.FlZtBzWMLJ9sP3i24u2i5rGHVY-i1VQJBK4aU19Tvgc
###
 #leave a class by class code
POST http://localhost:8000/api/class/3CYILX9/leave/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5ODY2MzA5LCJpYXQiOjE3NTk4NjUxMDksImp0aSI6ImU2MjIzMjlhNGQzZTQ0ZTA4NTdmNTQ2YzRlOWMxZDI1IiwidXNlcl9pZCI6IjExY2NmNDMwLTg5NmItNDA4Mi04MTAzLTZhM2ZjMjdjNGJkNiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIn0.FlZtBzWMLJ9sP3i24u2i5rGHVY-i1VQJBK4aU19Tvgc